### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function

### ISSUE THREAD

**Issue by kayintveen** [fridays/next-routes#286]
I just got the following issues when making a simple link.
when removing the link the error will disappear:

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

```
<Link route="product" params={{ slug: "a-product-url" }}>
    <a>Product link!</a>
</Link>
```

full stack trace
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
    at invariant (/Users/user/Sites/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:58:15)
    at ReactDOMServerRenderer.render (/Users/user/Sites/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:7)
    at ReactDOMServerRenderer.read (/Users/user/Sites/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3131:29)
    at renderToString (/Users/user/Sites/project/node_modules/react-dom/cjs/react-dom-server.node.development.js:3598:27)
    at render (/Users/user/Sites/project/node_modules/next-server/dist/server/render.js:39:16)
    at renderPage (/Users/user/Sites/project/node_modules/next-server/dist/server/render.js:95:16)
    at Function.getInitialProps (/Users/user/Sites/project/.next/server/static/development/pages/_document.js:499:25)
    at Object.loadGetInitialProps (/Users/user/Sites/project/node_modules/next-server/dist/lib/utils.js:44:35)
    at Object.renderToHTML (/Users/user/Sites/project/node_modules/next-server/dist/server/render.js:98:36)
```

**Comment by miateeny** [comment]
Probably you have `import Link from './routes'`
Try to use `import { Link } from './routes'` instead
