### ISSUE TITLE
Update npm pagekage in Nextjs 8.0

### ISSUE THREAD

**Issue by maihungdev** [fridays/next-routes#303]
Hi, thank to package.

Recently, nextjs updated struct foder, and now package have a issue

Error: Cannot find module 'next/dist/lib/link.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

i fixed by change:

var _link = require('next/dist/lib/link.js'); 
to
var _link = require('next/link.js');

var _index = require('next/dist/lib/router/index.js');
to
var _index = require('next/router.js');

**Comment by maihungdev** [comment]
Pakeage in packeage.json 

 "next": "^4.1.4",

can you update package? packeage only update in git, not npmjs

to
 "next": "^8.1.0",

**Comment by maihungdev** [comment]
sorry, i posted another package!
